#!/usr/bin/env bash
# One-time droplet provisioning script.
# Run as root on a fresh Ubuntu 24.04 droplet:
#   curl -fsSL https://raw.githubusercontent.com/anthonychu-spec/go24-mobile/main/infra/droplet/setup.sh | sudo bash

set -euo pipefail

# Force non-interactive apt — never prompt for config conflicts.
# Always keep currently-installed config files.
export DEBIAN_FRONTEND=noninteractive
APT_OPTS="-o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef"

echo "=== GO24 droplet provisioning ==="

# --- 1. System update + basics ---
apt-get update -y
apt-get -y $APT_OPTS upgrade
apt-get -y $APT_OPTS install \
  curl wget git ufw fail2ban htop vim \
  ca-certificates gnupg lsb-release unattended-upgrades

# --- 2. Auto-security-updates ---
dpkg-reconfigure -p low unattended-upgrades || true

# --- 3. Firewall (allow SSH + HTTP/S only) ---
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

# --- 4. Fail2ban for SSH brute force ---
systemctl enable --now fail2ban

# --- 5. Docker Engine + Compose plugin ---
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update -y
apt-get -y $APT_OPTS install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# --- 6. Create deploy user ---
if ! id -u deploy >/dev/null 2>&1; then
  adduser --disabled-password --gecos '' deploy
  usermod -aG docker deploy
  echo "deploy ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart go24, /usr/bin/docker, /usr/bin/docker-compose, /usr/local/bin/docker compose" >> /etc/sudoers
  mkdir -p /home/deploy/.ssh
  chmod 700 /home/deploy/.ssh
  cp /root/.ssh/authorized_keys /home/deploy/.ssh/
  chown -R deploy:deploy /home/deploy/.ssh
  chmod 600 /home/deploy/.ssh/authorized_keys
fi

# --- 7. SSH hardening (do BEFORE making project dir) ---
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl reload ssh

# --- 8. Swap (helpful for 4GB droplets running Postgres) ---
if [ ! -f /swapfile ]; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# --- 9. Ops dir (backup script + logs — separate from repo dir) ---
mkdir -p /opt/go24-ops/backups
cat > /opt/go24-ops/backup.sh <<'BACKUP'
#!/bin/bash
set -euo pipefail
TS=$(date +%Y%m%d-%H%M%S)
docker exec go24-postgres pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB" | gzip > /opt/go24-ops/backups/db-$TS.sql.gz
# Keep last 30 days
find /opt/go24-ops/backups -name 'db-*.sql.gz' -mtime +30 -delete
BACKUP
chmod +x /opt/go24-ops/backup.sh
chown -R deploy:deploy /opt/go24-ops
echo '0 3 * * * deploy /opt/go24-ops/backup.sh >> /var/log/go24-backup.log 2>&1' > /etc/cron.d/go24-backup

# --- 10. Project dir + auto-clone repo as deploy ---
mkdir -p /opt/go24
chown deploy:deploy /opt/go24

if [ ! -d /opt/go24/.git ]; then
  echo "→ cloning repo into /opt/go24"
  sudo -u deploy git clone https://github.com/anthonychu-spec/go24-mobile.git /opt/go24
else
  echo "→ /opt/go24 already a git repo, pulling latest"
  sudo -u deploy bash -c "cd /opt/go24 && git fetch origin main && git reset --hard origin/main"
fi

# --- 11. Generate .env from template (with random secrets pre-filled) ---
if [ ! -f /opt/go24/.env ]; then
  POSTGRES_PWD=$(openssl rand -hex 24)
  REDIS_PWD=$(openssl rand -hex 24)
  JWT_SEC=$(openssl rand -hex 32)
  sudo -u deploy tee /opt/go24/.env >/dev/null <<ENV
# Auto-generated by setup.sh — fill in PGM_* + API_DOMAIN before docker compose up
NODE_ENV=production
PORT=3000

POSTGRES_USER=go24
POSTGRES_PASSWORD=$POSTGRES_PWD
POSTGRES_DB=go24

REDIS_PASSWORD=$REDIS_PWD

JWT_SECRET=$JWT_SEC
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=30d

# === FILL THESE BEFORE STARTING ===
PGM_API_BASE=https://go24fitness-hk.perfectgym.pl/Api/v2.2
PGM_CLIENT_ID=
PGM_CLIENT_SECRET=
PGM_OTP_DESTINATION=Email

API_DOMAIN=api-staging.go24.fitness
ENV
  chmod 600 /opt/go24/.env
  echo "→ Generated /opt/go24/.env with random secrets (PGM_* + API_DOMAIN to fill)"
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "Repo cloned at:  /opt/go24"
echo "Env file at:     /opt/go24/.env  (random secrets generated; PGM_* + API_DOMAIN pending)"
echo "Backup script:   /opt/go24-ops/backup.sh (cron @ 3am daily)"
echo ""
echo "Next steps (as deploy user):"
echo "  sudo -u deploy bash"
echo "  cd /opt/go24"
echo "  nano .env                       # fill PGM_CLIENT_ID, PGM_CLIENT_SECRET, API_DOMAIN"
echo "  docker compose -f infra/droplet/docker-compose.prod.yml up -d --build"
echo ""
echo "  Point Cloudflare DNS A record for \$API_DOMAIN to this droplet IP."
echo ""
echo "Logs:    docker compose -f infra/droplet/docker-compose.prod.yml logs -f api"
echo "Restart: docker compose -f infra/droplet/docker-compose.prod.yml restart api"
